/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.*;
import java.awt.event.ActionEvent;
/**
 *
 * @author JKD
 */
public class TicTacToe extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TicTacToe.class.getName());
    
    private boolean playerX = true; // true = X, false = O
    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
        addActions();
        setTitle("Tic Tac Toe Game");
        setResizable(false);
        
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("logo.png")).getImage());
        
    }
    
    private void addActions() {
        javax.swing.JButton[] buttons = {b0,b1,b2,b3,b4,b5,b6,b7,b8};

        for (javax.swing.JButton btn : buttons) {
            btn.setFont(new java.awt.Font("Arial", 1, 24));

            // ✅ FIXED SIZE
            btn.setPreferredSize(new java.awt.Dimension(70, 70));
            btn.setMinimumSize(new java.awt.Dimension(70, 70));
            btn.setMaximumSize(new java.awt.Dimension(70, 70));

            btn.addActionListener(e -> buttonClicked(btn)); // ✅ ONLY ONCE
        }

        btnReset.addActionListener(e -> resetGame());
    }

    private void buttonClicked(javax.swing.JButton btn) {
        if (!btn.getText().equals("")) return;

        String currentPlayer;

        if (playerX) {
            btn.setText("X");
            btn.setForeground(java.awt.Color.BLUE);
            currentPlayer = "X";
        } else {
            btn.setText("O");
            btn.setForeground(java.awt.Color.RED);
            currentPlayer = "O";
        }

        // ✅ Check winner BEFORE switching turn
        if (checkWinner(currentPlayer)) return;

        playerX = !playerX; // switch after checking
    }

    private boolean checkWinner(String player) {
        String[][] b = {
            {b0.getText(), b1.getText(), b2.getText()},
            {b3.getText(), b4.getText(), b5.getText()},
            {b6.getText(), b7.getText(), b8.getText()}
        };

        for (int i = 0; i < 3; i++) {
            if (b[i][0].equals(player) && b[i][1].equals(player) && b[i][2].equals(player)) {
                showWinner(player);
                return true;
            }
            if (b[0][i].equals(player) && b[1][i].equals(player) && b[2][i].equals(player)) {
                showWinner(player);
                return true;
            }
        }

        if (b[0][0].equals(player) && b[1][1].equals(player) && b[2][2].equals(player)) {
            showWinner(player);
            return true;
        }

        if (b[0][2].equals(player) && b[1][1].equals(player) && b[2][0].equals(player)) {
            showWinner(player);
            return true;
        }

        // draw check
        boolean isDraw = true;
        for (javax.swing.JButton btn : new javax.swing.JButton[]{b0,b1,b2,b3,b4,b5,b6,b7,b8}) {
            if (btn.getText().equals("")) {
                isDraw = false;
                break;
            }
        }

        if (isDraw) {
            javax.swing.JOptionPane.showMessageDialog(this, "Match Draw!");
            resetGame();
            return true;
        }

        return false;
    }

    private void showWinner(String winner) {
        javax.swing.JOptionPane.showMessageDialog(this, winner + " Wins!");
        resetGame();
    }

    private void resetGame() {
        javax.swing.JButton[] buttons = {b0,b1,b2,b3,b4,b5,b6,b7,b8};

        for (javax.swing.JButton btn : buttons) {
            btn.setText("");
            btn.setForeground(java.awt.Color.BLACK); // reset color
        }

        playerX = true;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b0 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe");

        b4.addActionListener(this::b4ActionPerformed);

        btnReset.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b3)
                        .addGap(18, 18, 18)
                        .addComponent(b4)
                        .addGap(18, 18, 18)
                        .addComponent(b5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(b0)
                        .addGap(18, 18, 18)
                        .addComponent(b1)
                        .addGap(18, 18, 18)
                        .addComponent(b2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReset)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b6)
                                .addGap(18, 18, 18)
                                .addComponent(b7)))
                        .addGap(18, 18, 18)
                        .addComponent(b8)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b0, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TicTacToe().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
     
}
